sql = """SELECT
    NR_SEQUENCIA,
    NR_ATENDIMENTO,
    DT_PRIM_HORARIO,
    DS_TURNO,
	CD_SETOR_ATENDIMENTO,
    DS_SETOR_LOTE,
    DS_LEITO,
    IE_ATB,
    DT_GERACAO_LOTE,
    DT_INICIO_TURNO,
	TO_CHAR(DT_ENTREGA_PREVISTA,'DD/MM HH24:MI')DT_ENTREGA_PREVISTA,
    IE_REAPRAZADO_GRID,
    ROUND(CALCULAR_DIFERENCA_EM_MINUTOS(TO_CHAR(SYSDATE,'dd/mm/yyyy hh24:mi'),TO_CHAR(DT_ENTREGA_PREVISTA,'dd/mm/yyyy hh24:mi')))TEMPO_RESTANTE
    
FROM HCD_GV_LOTES_CD_V
WHERE 1=1
AND DT_GERACAO_LOTE < DT_INICIO_TURNO"""