sql = """SELECT
    NR_SEQUENCIA,
    NR_ATENDIMENTO,
    DT_PRIM_HORARIO,
    DS_TURNO,
	CD_SETOR_ATENDIMENTO,
    DS_SETOR_LOTE,
    DS_LEITO,
    IE_ATB,
    DT_GERACAO_LOTE,
    DT_INICIO_TURNO,
	TO_CHAR(DT_ENTREGA_PREVISTA,'DD/MM HH24:MI')DT_ENTREGA_PREVISTA,
    IE_REAPRAZADO_GRID,
    ROUND(CALCULAR_DIFERENCA_EM_MINUTOS(TO_CHAR(SYSDATE,'dd/mm/yyyy hh24:mi'),TO_CHAR(DT_INICIO_TURNO,'dd/mm/yyyy hh24:mi')))TEMPO_RESTANTE
    
FROM HCD_GV_LOTES_CD_V
WHERE 1=1
AND DT_GERACAO_LOTE < DT_INICIO_TURNO"""

sql_aux = """SELECT
    NR_SEQUENCIA,
    NR_ATENDIMENTO,
    DT_PRIM_HORARIO,
    DS_TURNO,
	CD_SETOR_ATENDIMENTO,
    DS_SETOR_LOTE,
    DS_LEITO,
    IE_ATB,
    DT_GERACAO_LOTE,
    DT_INICIO_TURNO,
	TO_CHAR(DT_LIMITE_ATENDIMENTO,'DD/MM HH24:MI')DT_LIMITE_ATENDIMENTO,
    ROUND(CALCULAR_DIFERENCA_EM_MINUTOS(TO_CHAR(SYSDATE,'dd/mm/yyyy hh24:mi'),TO_CHAR(DT_INICIO_TURNO,'dd/mm/yyyy hh24:mi')))TEMPO_RESTANTE,
    DS_STATUS_LOTE
    
FROM HCD_GV_LOTES_CD_V2
WHERE 1=1
AND ((SYSDATE BETWEEN DT_INICIO_ATEND_LOTE AND DT_LIMITE_ATENDIMENTO) OR ((DT_INICIO_ATEND_LOTE BETWEEN TO_DATE(TO_CHAR(SYSDATE,'dd/mm/yyyy') || ' 00:00:00', 'dd/mm/yyyy hh24:mi:ss') AND SYSDATE) AND (DS_STATUS_LOTE = 'Gerado')))
AND (DT_ALTERACAO_TURNO < DT_LIMITE_ATENDIMENTO or DT_ALTERACAO_TURNO IS NULL)
AND DT_GERACAO_LOTE < DT_LIMITE_ATENDIMENTO
"""